; PlatformIO Project Configuration File

[platformio]
default_envs =
	esp32-N4
extra_configs =
	platformio.local.ini

[env]
lib_deps =
	bitbank2/bb_epaper@^2.1.9
	nodaoli/ArduinoUZlib@^1.0.2
	h2zero/NimBLE-Arduino@^2.5.0

[mirror]
github = https://ghfast.top/https://github.com
esp32_platform = ${mirror.github}/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

[env:nrf52840custom]
build_flags =
	-DTARGET_NRF
platform = nordicnrf52
framework = arduino
board_build.variants_dir = variants
board_build.variant = nrf52840custom
board = xiaoblesense_adafruit
monitor_speed = 115200
build_src_filter = +<*> -<main_mbed.cpp>
lib_ignore = Seeed_GFX

[env:esp32-s3-N16R8]
platform = ${mirror.esp32_platform}
framework = arduino
platform_packages =
	tool-esp_install@${mirror.github}/pioarduino/esp_install/releases/download/v5.3.4/esp_install-v5.3.4.zip
	framework-arduinoespressif32@${mirror.github}/espressif/arduino-esp32/releases/download/3.3.8/esp32-core-3.3.8.tar.xz
	framework-arduinoespressif32-libs@${mirror.github}/espressif/arduino-esp32/releases/download/3.3.8/esp32-core-3.3.8-libs.tar.xz
	toolchain-xtensa-esp-elf@${mirror.github}/pioarduino/registry/releases/download/0.0.1/xtensa-esp-elf-14.2.0_20260121.zip
	toolchain-riscv32-esp@${mirror.github}/pioarduino/registry/releases/download/0.0.1/riscv32-esp-elf-14.2.0_20260121.zip
	toolchain-esp32ulp@${mirror.github}/pioarduino/registry/releases/download/0.0.1/esp32ulp-elf-2.38_20240113.zip
	tool-xtensa-esp-elf-gdb@${mirror.github}/pioarduino/registry/releases/download/0.0.1/xtensa-esp-gdb-16.3_20250913.zip
	tool-riscv32-esp-elf-gdb@${mirror.github}/pioarduino/registry/releases/download/0.0.1/riscv32-esp-gdb-16.3_20250913.zip
	contrib-piohome@${mirror.github}/pioarduino/registry/releases/download/0.0.1/contrib-piohome-3.4.4.tar.gz
	tool-esptoolpy@${mirror.github}/pioarduino/registry/releases/download/0.0.1/esptoolpy-v5.2.0.zip
build_flags =
	-DTARGET_ESP32
	-DTARGET_LARGE_MEMORY
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCONFIG_FREERTOS_WATCHDOG_TIMEOUT_S=120
	-DOPENDISPLAY_SEEED_GFX
board_build.filesystem = littlefs
board = esp32-s3-devkitc-1
board_build.partitions = default_16MB.csv
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.psram_type = qspi_opi
board_build.usb_mode = hardware
board_upload.maximum_size = 16777216
board_upload.maximum_ram_size = 327680
board_upload.flash_size = 16MB
monitor_speed = 115200

[env:esp32-s3-N8R8]
platform = ${mirror.esp32_platform}
framework = arduino
platform_packages =
	tool-esp_install@${mirror.github}/pioarduino/esp_install/releases/download/v5.3.4/esp_install-v5.3.4.zip
	framework-arduinoespressif32@${mirror.github}/espressif/arduino-esp32/releases/download/3.3.8/esp32-core-3.3.8.tar.xz
	framework-arduinoespressif32-libs@${mirror.github}/espressif/arduino-esp32/releases/download/3.3.8/esp32-core-3.3.8-libs.tar.xz
	toolchain-xtensa-esp-elf@${mirror.github}/pioarduino/registry/releases/download/0.0.1/xtensa-esp-elf-14.2.0_20260121.zip
	toolchain-riscv32-esp@${mirror.github}/pioarduino/registry/releases/download/0.0.1/riscv32-esp-elf-14.2.0_20260121.zip
	toolchain-esp32ulp@${mirror.github}/pioarduino/registry/releases/download/0.0.1/esp32ulp-elf-2.38_20240113.zip
	tool-xtensa-esp-elf-gdb@${mirror.github}/pioarduino/registry/releases/download/0.0.1/xtensa-esp-gdb-16.3_20250913.zip
	tool-riscv32-esp-elf-gdb@${mirror.github}/pioarduino/registry/releases/download/0.0.1/riscv32-esp-gdb-16.3_20250913.zip
	contrib-piohome@${mirror.github}/pioarduino/registry/releases/download/0.0.1/contrib-piohome-3.4.4.tar.gz
	tool-esptoolpy@${mirror.github}/pioarduino/registry/releases/download/0.0.1/esptoolpy-v5.2.0.zip
build_flags =
	-DTARGET_ESP32
	-DTARGET_LARGE_MEMORY
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCONFIG_FREERTOS_WATCHDOG_TIMEOUT_S=120
	-DOPENDISPLAY_SEEED_GFX
board_build.filesystem = littlefs
board = esp32-s3-devkitc-1
board_build.partitions = default_8MB.csv
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.psram_type = qspi_opi
board_build.usb_mode = hardware
board_upload.maximum_size = 8388608
board_upload.maximum_ram_size = 327680
board_upload.flash_size = 8MB
monitor_speed = 115200

[env:esp32-s3-N32R8]
platform = ${mirror.esp32_platform}
framework = arduino
platform_packages =
	tool-esp_install@${mirror.github}/pioarduino/esp_install/releases/download/v5.3.4/esp_install-v5.3.4.zip
	framework-arduinoespressif32@${mirror.github}/espressif/arduino-esp32/releases/download/3.3.8/esp32-core-3.3.8.tar.xz
	framework-arduinoespressif32-libs@${mirror.github}/espressif/arduino-esp32/releases/download/3.3.8/esp32-core-3.3.8-libs.tar.xz
	toolchain-xtensa-esp-elf@${mirror.github}/pioarduino/registry/releases/download/0.0.1/xtensa-esp-elf-14.2.0_20260121.zip
	toolchain-riscv32-esp@${mirror.github}/pioarduino/registry/releases/download/0.0.1/riscv32-esp-elf-14.2.0_20260121.zip
	toolchain-esp32ulp@${mirror.github}/pioarduino/registry/releases/download/0.0.1/esp32ulp-elf-2.38_20240113.zip
	tool-xtensa-esp-elf-gdb@${mirror.github}/pioarduino/registry/releases/download/0.0.1/xtensa-esp-gdb-16.3_20250913.zip
	tool-riscv32-esp-elf-gdb@${mirror.github}/pioarduino/registry/releases/download/0.0.1/riscv32-esp-gdb-16.3_20250913.zip
	contrib-piohome@${mirror.github}/pioarduino/registry/releases/download/0.0.1/contrib-piohome-3.4.4.tar.gz
	tool-esptoolpy@${mirror.github}/pioarduino/registry/releases/download/0.0.1/esptoolpy-v5.2.0.zip
build_flags =
	-DTARGET_ESP32
	-DTARGET_LARGE_MEMORY
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCONFIG_FREERTOS_WATCHDOG_TIMEOUT_S=120
	-DOPENDISPLAY_SEEED_GFX
board_build.filesystem = littlefs
board = esp32-s3-devkitc-1
board_build.partitions = default_32MB.csv
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.psram_type = qspi_opi
board_build.usb_mode = hardware
board_upload.maximum_size = 33554432
board_upload.maximum_ram_size = 327680
board_upload.flash_size = 32MB
monitor_speed = 115200

[env:esp32-c3-N4]
platform = ${mirror.esp32_platform}
framework = arduino
platform_packages =
	tool-esp_install@${mirror.github}/pioarduino/esp_install/releases/download/v5.3.4/esp_install-v5.3.4.zip
	framework-arduinoespressif32@${mirror.github}/espressif/arduino-esp32/releases/download/3.3.8/esp32-core-3.3.8.tar.xz
	framework-arduinoespressif32-libs@${mirror.github}/espressif/arduino-esp32/releases/download/3.3.8/esp32-core-3.3.8-libs.tar.xz
	toolchain-xtensa-esp-elf@${mirror.github}/pioarduino/registry/releases/download/0.0.1/xtensa-esp-elf-14.2.0_20260121.zip
	toolchain-riscv32-esp@${mirror.github}/pioarduino/registry/releases/download/0.0.1/riscv32-esp-elf-14.2.0_20260121.zip
	toolchain-esp32ulp@${mirror.github}/pioarduino/registry/releases/download/0.0.1/esp32ulp-elf-2.38_20240113.zip
	tool-xtensa-esp-elf-gdb@${mirror.github}/pioarduino/registry/releases/download/0.0.1/xtensa-esp-gdb-16.3_20250913.zip
	tool-riscv32-esp-elf-gdb@${mirror.github}/pioarduino/registry/releases/download/0.0.1/riscv32-esp-gdb-16.3_20250913.zip
	contrib-piohome@${mirror.github}/pioarduino/registry/releases/download/0.0.1/contrib-piohome-3.4.4.tar.gz
	tool-esptoolpy@${mirror.github}/pioarduino/registry/releases/download/0.0.1/esptoolpy-v5.2.0.zip
build_flags =
	-DTARGET_ESP32
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCONFIG_FREERTOS_WATCHDOG_TIMEOUT_S=120
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv
board = esp32-c3-devkitm-1
monitor_speed = 115200
lib_ignore = Seeed_GFX

[env:esp32-c6-N4]
platform = ${mirror.esp32_platform}
framework = arduino
platform_packages =
	tool-esp_install@${mirror.github}/pioarduino/esp_install/releases/download/v5.3.4/esp_install-v5.3.4.zip
	framework-arduinoespressif32@${mirror.github}/espressif/arduino-esp32/releases/download/3.3.8/esp32-core-3.3.8.tar.xz
	framework-arduinoespressif32-libs@${mirror.github}/espressif/arduino-esp32/releases/download/3.3.8/esp32-core-3.3.8-libs.tar.xz
	toolchain-xtensa-esp-elf@${mirror.github}/pioarduino/registry/releases/download/0.0.1/xtensa-esp-elf-14.2.0_20260121.zip
	toolchain-riscv32-esp@${mirror.github}/pioarduino/registry/releases/download/0.0.1/riscv32-esp-elf-14.2.0_20260121.zip
	toolchain-esp32ulp@${mirror.github}/pioarduino/registry/releases/download/0.0.1/esp32ulp-elf-2.38_20240113.zip
	tool-xtensa-esp-elf-gdb@${mirror.github}/pioarduino/registry/releases/download/0.0.1/xtensa-esp-gdb-16.3_20250913.zip
	tool-riscv32-esp-elf-gdb@${mirror.github}/pioarduino/registry/releases/download/0.0.1/riscv32-esp-gdb-16.3_20250913.zip
	contrib-piohome@${mirror.github}/pioarduino/registry/releases/download/0.0.1/contrib-piohome-3.4.4.tar.gz
	tool-esptoolpy@${mirror.github}/pioarduino/registry/releases/download/0.0.1/esptoolpy-v5.2.0.zip
build_flags =
	-DTARGET_ESP32
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCONFIG_FREERTOS_WATCHDOG_TIMEOUT_S=120
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv
board = esp32-c6-devkitm-1
monitor_speed = 115200
lib_ignore = Seeed_GFX

[env:esp32-s3-N16R8-extuart]
platform = ${mirror.esp32_platform}
framework = arduino
platform_packages =
	tool-esp_install@${mirror.github}/pioarduino/esp_install/releases/download/v5.3.4/esp_install-v5.3.4.zip
	framework-arduinoespressif32@${mirror.github}/espressif/arduino-esp32/releases/download/3.3.8/esp32-core-3.3.8.tar.xz
	framework-arduinoespressif32-libs@${mirror.github}/espressif/arduino-esp32/releases/download/3.3.8/esp32-core-3.3.8-libs.tar.xz
	toolchain-xtensa-esp-elf@${mirror.github}/pioarduino/registry/releases/download/0.0.1/xtensa-esp-elf-14.2.0_20260121.zip
	toolchain-riscv32-esp@${mirror.github}/pioarduino/registry/releases/download/0.0.1/riscv32-esp-elf-14.2.0_20260121.zip
	toolchain-esp32ulp@${mirror.github}/pioarduino/registry/releases/download/0.0.1/esp32ulp-elf-2.38_20240113.zip
	tool-xtensa-esp-elf-gdb@${mirror.github}/pioarduino/registry/releases/download/0.0.1/xtensa-esp-gdb-16.3_20250913.zip
	tool-riscv32-esp-elf-gdb@${mirror.github}/pioarduino/registry/releases/download/0.0.1/riscv32-esp-gdb-16.3_20250913.zip
	contrib-piohome@${mirror.github}/pioarduino/registry/releases/download/0.0.1/contrib-piohome-3.4.4.tar.gz
	tool-esptoolpy@${mirror.github}/pioarduino/registry/releases/download/0.0.1/esptoolpy-v5.2.0.zip
build_flags =
	-DTARGET_ESP32
	-DTARGET_LARGE_MEMORY
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCONFIG_FREERTOS_WATCHDOG_TIMEOUT_S=120
	-DOPENDISPLAY_SEEED_GFX
	-DOPENDISPLAY_LOG_UART
	-DOPENDISPLAY_LOG_UART_RX=44
	-DOPENDISPLAY_LOG_UART_TX=43
board_build.filesystem = littlefs
board = esp32-s3-devkitc-1
board_build.partitions = default_16MB.csv
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.psram_type = qspi_opi
board_build.usb_mode = hardware
board_upload.maximum_size = 16777216
board_upload.maximum_ram_size = 327680
board_upload.flash_size = 16MB
monitor_speed = 115200

[env:esp32-N4]
platform = ${mirror.esp32_platform}
framework = arduino
platform_packages =
	tool-esp_install@${mirror.github}/pioarduino/esp_install/releases/download/v5.3.4/esp_install-v5.3.4.zip
	framework-arduinoespressif32@${mirror.github}/espressif/arduino-esp32/releases/download/3.3.8/esp32-core-3.3.8.tar.xz
	framework-arduinoespressif32-libs@${mirror.github}/espressif/arduino-esp32/releases/download/3.3.8/esp32-core-3.3.8-libs.tar.xz
	toolchain-esp32ulp@${mirror.github}/pioarduino/registry/releases/download/0.0.1/esp32ulp-elf-2.38_20240113.zip
	tool-xtensa-esp-elf-gdb@${mirror.github}/pioarduino/registry/releases/download/0.0.1/xtensa-esp-gdb-16.3_20250913.zip
	tool-riscv32-esp-elf-gdb@${mirror.github}/pioarduino/registry/releases/download/0.0.1/riscv32-esp-gdb-16.3_20250913.zip
	contrib-piohome@${mirror.github}/pioarduino/registry/releases/download/0.0.1/contrib-piohome-3.4.4.tar.gz
	tool-esptoolpy@${mirror.github}/pioarduino/registry/releases/download/0.0.1/esptoolpy-v5.2.0.zip
build_flags =
	-DTARGET_ESP32
	-DCONFIG_FREERTOS_WATCHDOG_TIMEOUT_S=120
	-DOPENDISPLAY_BOARD_ESP32_N4_42R
board_build.filesystem = littlefs
board = esp32dev
board_build.partitions = huge_app.csv
monitor_speed = 115200
lib_ignore = Seeed_GFX
