; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = Ink Screen Calendar
default_envs = 
	z21
	z15
	z98
	1680

[common]
framework = arduino
lib_deps = 
	olikraus/U8g2_for_Adafruit_GFX@^1.8.0
	h2zero/NimBLE-Arduino@^2.5.0
dashboard_src_filter =
	+<main.cpp>
	+<app_state.cpp>
	+<ble_service.cpp>
	+<dashboard_protocol.cpp>
	+<dashboard_renderer.cpp>
	+<display_service.cpp>
	+<protocol.cpp>

[env:1680]
build_type = release
platform = espressif32
board = esp32dev
framework = ${common.framework}
lib_deps = ${common.lib_deps}
build_src_filter = ${common.dashboard_src_filter}
upload_speed = 921600
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_flags = -D SI_DRIVER=1680

[env:z98]
build_type = release
platform = espressif32
board = esp32dev
framework = ${common.framework}
lib_deps = ${common.lib_deps}
build_src_filter = ${common.dashboard_src_filter}
upload_speed = 460800
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_flags = -D SI_DRIVER=98

[env:z21]
build_type = release
platform = espressif32
board = esp32dev
framework = ${common.framework}
lib_deps = ${common.lib_deps}
build_src_filter = ${common.dashboard_src_filter}
upload_speed = 460800
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_flags = -D SI_DRIVER=21

[env:z15]
build_type = release
platform = espressif32
board = esp32dev
framework = ${common.framework}
lib_deps = ${common.lib_deps}
build_src_filter = ${common.dashboard_src_filter}
upload_speed = 460800
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_flags = -D SI_DRIVER=15


[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
board_build.flash_mode = dio
framework = ${common.framework}
lib_deps = ${common.lib_deps}
upload_speed = 460800
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_flags = -D SI_DRIVER=98
;	-DARDUINO_USB_MODE=1
;	-DARDUINO_USB_CDC_ON_BOOT=1
